services:
  client:
    container_name: local-client
    image: local-client:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    depends_on:
      signer:
        condition: service_healthy
    environment:
      CLIENT_ENV_FILE_PATH: local_volume/.env
    volumes:
      - "${CLIENT_VOLUME_DIR:-./client_volume}:/usr/src/app/client_volume"
      - "local-data:/usr/src/app/local_volume"
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  signer:
    container_name: local-signer
    image: local-signer:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    depends_on:
      setup:
        condition: service_completed_successfully
        restart: true
      localstack:
        condition: service_started
    environment:
      ENV_FILE_PATH: local_volume/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://signer:5000/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    ports:
      - 5001:5000
    volumes:
      - "local-data:/usr/src/app/local_volume"
  setup:
    container_name: local-setup
    image: local-setup:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: local-setup
    environment:
      ENV_FILE_PATH: .env.local
    volumes:
      - "local-data:/usr/src/app/local_volume"
volumes:
  local-data:
